DELETE http://localhost:3001/api/notes/62aa5b239a7bfc1b1b845c28

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "this is the content",
  "important": true
}

###

GET http://localhost:3001/api/notes

###

PUT http://localhost:3001/api/notes/62aa68c0fe3cfb4320350483
Content-Type: application/json

{
  "content": "this is the updated content",
  "important": false
}